In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [8]:
x=torch.rand(2,20)
x

tensor([[0.9596, 0.8182, 0.5110, 0.6206, 0.3600, 0.5617, 0.6610, 0.4387, 0.5112,
         0.9972, 0.2526, 0.5971, 0.0322, 0.8156, 0.7839, 0.9746, 0.6571, 0.8001,
         0.5706, 0.5718],
        [0.3359, 0.5953, 0.7211, 0.1227, 0.9040, 0.9644, 0.3645, 0.1438, 0.0934,
         0.4524, 0.8171, 0.6789, 0.7734, 0.0078, 0.2854, 0.3359, 0.9255, 0.2190,
         0.9357, 0.3690]])

In [3]:
net=nn.Sequential(nn.Linear(20,256),nn.ReLU(),nn.Linear(256,10))
net(x)

tensor([[ 0.0778,  0.2849, -0.1687,  0.0344, -0.1148, -0.0494,  0.1902,  0.0419,
         -0.1769,  0.0445],
        [ 0.0791,  0.2757, -0.1600,  0.0592, -0.0320, -0.0162,  0.2524, -0.0094,
         -0.1744,  0.0748]], grad_fn=<AddmmBackward0>)

In [ ]:
#构建一个自己的类，实现和sequential类一样的功能
class MySequential(nn.Module):
    def __init__(self,*args):
        super().__init__()
        for idx,module in enumerate(args):
            self._modules[str(idx)]=module 
    
    def forward(self,x):
        for block in self._modules.values():#values()是一个方法！括号不可省
            x=block(x)
        return x

net2=MySequential(nn.Linear(20,256),nn.ReLU(),nn.Linear(256,10))
net2(x)

tensor([[-4.6158e-02,  2.3660e-01, -1.1163e-01, -1.9590e-01, -1.2612e-02,
         -1.7347e-01, -3.3502e-01,  8.7561e-02, -7.4558e-02,  2.6319e-01],
        [-2.4958e-04,  6.5260e-02, -2.5039e-01, -1.3955e-01, -1.9888e-01,
         -2.9041e-01, -1.5157e-01,  5.2006e-02, -1.1413e-01,  2.1962e-01]],
       grad_fn=<AddmmBackward0>)

In [18]:
#参数访问
network=nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
# print(network.state_dict()) #一次性访问所有参数
#print(network[2].state_dict()) #只访问第二层的参数，为一个OrderedDict
#network[2].weight.grad==None
print(*[(name,param.shape) for name,param in network[0].named_parameters()])
print(*[(name,param.shape) for name,param in network.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [20]:
#根据上面的输出得到启发
network.state_dict()['2.bias'].data

tensor([-0.2095])

In [21]:
!nvidia-smi

Wed Apr 23 19:00:13 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.61                 Driver Version: 572.61         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce MX330         WDDM  |   00000000:03:00.0 Off |                  N/A |
| N/A   45C    P0            N/A  / 5001W |       0MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [22]:
torch.cuda.device_count()

1