In [2]:
import torch
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd
data=pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [3]:
#数据预处理-处理缺失值
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())#把数值列的nan值用同列非nan值的均值替换
inputs=pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [6]:
#一个神奇的例子
naked_a=torch.arange(12)
naked_b=naked_a.reshape((3,4))
naked_b[:]=2
naked_a,id(naked_a),id(naked_b)

(tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 2336574966016, 2336574966336)

In [6]:
x=torch.arange(4.0)
x.requires_grad_(True)
y=2*torch.dot(x,x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad==4*x

tensor([True, True, True, True])

In [ ]:
x.grad.zero_()#默认情况下，pytorch会累积梯度，因此需要清除之前的值
y=x.sum()
y.backward()
x.grad

tensor([3., 3., 3., 3.])

In [ ]:
x.grad.zero_()
y=x*x #y为向量！但在深度学习领域，绝大部分都是对标量求导
#y.sum().backward()
y.backward(torch.ones(len(x)))
x.grad

In [6]:
y_hat=torch.tensor([[1,3,6],[3,2,5]])
y_hat.shape[1]

3